force-app/main/default/objects/Asset_Assignment__c/Asset_Assignment__c.object-meta.xml
<CustomObject>
    <label>Asset Assignment</label>
    <nameField>
        <label>Asset Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset_Assignment__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Asset Assignments</relationshipLabel>
    <relationshipName>Asset_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_Assignment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Asset Assignments</relationshipLabel>
    <relationshipName>Asset_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssetServiceTest.cls
@isTest
private class AssetServiceTest {

    @isTest
    static void testAssignAsset() {

        Employee__c emp = new Employee__c(
            Name = 'John'
        );
        insert emp;

       Asset__c asset = new Asset__c(
    Name = 'Dell Laptop',
    Status__c = 'Available'
);
        insert asset;

        Test.startTest();

        Asset_Assignment__c assignment =
            AssetService.assignAsset(

                emp.Id,
                asset.Id,
                Date.today(),
                Date.today().addDays(30)

            );

        Test.stopTest();

        System.assertNotEquals(
            null,
            assignment.Id
        );

    }

}