force-app/main/default/objects/Asset_Assignment__c/Asset_Assignment__c.object-meta.xml
<CustomObject>
    <label>Asset Assignment</label>
    <nameField>
        <label>Asset Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset_Assignment__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Asset Assignments</relationshipLabel>
    <relationshipName>Asset_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_Assignment__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Employee</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Asset Assignments</relationshipLabel>
    <relationshipName>Asset_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssetService.cls
public with sharing class AssetService {

    public static Asset_Assignment__c assignAsset(
        Id employeeId,
        Id assetId,
        Date assignedDate,
        Date expectedReturnDate
    ) {

        Asset__c asset = [
            SELECT Id, Status__c
            FROM Asset__c
            WHERE Id = :assetId
            LIMIT 1
        ];

        if (asset.Status__c != 'Available') {
            throw new AuraHandledException('Asset is already assigned.');
        }

        Asset_Assignment__c assignment = new Asset_Assignment__c();

        assignment.Employee__c = employeeId;
        assignment.Asset__c = assetId;
        assignment.Assigned_Date__c = assignedDate;
        assignment.Expected_Return_Date__c = expectedReturnDate;
        assignment.Status__c = 'Assigned';

        insert assignment;

        asset.Status__c = 'Assigned';
        update asset;

        return assignment;
    }

}