force-app/main/default/objects/Asset_Assignment__c/Asset_Assignment__c.object-meta.xml
<CustomObject>
    <label>Asset Assignment</label>
    <nameField>
        <label>Asset Assignment</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset Assignments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Asset_Assignment__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Asset Assignments</relationshipLabel>
    <relationshipName>Asset_Assignments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset_Assignment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
            <value>
                <fullName>Lost</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssetTriggerHandler.cls
public with sharing class AssetTriggerHandler {

    public static void afterInsert(

        List<Asset_Assignment__c> assignments

    ) {

        List<Asset__c> assetsToUpdate = new List<Asset__c>();

        for (Asset_Assignment__c assignment : assignments) {

            assetsToUpdate.add(

                new Asset__c(

                    Id = assignment.Asset__c,

                    Status__c = 'Assigned'

                )

            );

        }

        if (!assetsToUpdate.isEmpty()) {

            update assetsToUpdate;

        }

    }

}